env:
  browser: true
  es2021: true
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: '2020'
  sourceType: 'module'
plugins:
  - 'react'
  - 'react-hooks'
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'airbnb'
rules:
  react/jsx-filename-extension:
    - error
    - extensions: [ '.js', '.jsx', '.ts', '.tsx' ]
  react/jsx-one-expression-per-line: off
  space-before-function-paren: off
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': [ "error" ]
  import/no-unresolved: off
  import/extensions: off
ignorePatterns: ['**/reportWebVitals.js']
